### PR TITLE
Set Holocene Mainnet Superchain activation

### PR DESCRIPTION
**Pull request by sebastianst**
Setting Holocene Mainnet activationt to
* `Thu 09 Jan 2025 18:00:01 UTC`
* unix timestamp `1736445601`

Chains covered by superchain time inheritance are:
* Base
* OP
* Orderly
* Lyra
* Metal
* Mode
* Zora
* Lisk
* Ethernity
* Binary (added in this PR to join Superchain times)

**All other mainnet chains will not inherit the activation, unless they join superchain activation times by setting their `superchain_time`.**

In draft until confirmed that all chains that want to join superchain upgrades are covered.

### CODE REVIEW

**Comment by opgitgovernance** [comment]
Detected nonzero diff in rollup config. This PR modifies the configuration of at least one chain in the registry, which may or may not have been intended. You can see the detail [here](https://circleci.com/gh/ethereum-optimism/superchain-registry/47816).

**Comment by opgitgovernance** [comment]
Detected nonzero diff in genesis. This PR modifies the genesis data of at least one chain in the registry, which may or may not have been intended. You can see the detail [here](https://circleci.com/gh/ethereum-optimism/superchain-registry/47815).

**Comment by emilianobonassi** [comment]
@sebastianst double confirming all good on our end. all the superchain registered chain have the superchain_time set and will fork in january

**Comment by sebastianst** [comment]
> @sebastianst double confirming all good on our end. all the superchain registered chain have the superchain_time set and will fork in january

Thanks @emilianobonassi 

The following chains have a `granite_time` and are therefore candidates for joining Superchain Holocene activations:
- Lisk :white_check_mark:
- Shape :question:
- Worldchain :question:
- Ethernity :white_check_mark:
- Binary :question:

✅ -> got feedback/PR for inclusion
❓ -> waiting for feedback

cc @ZakAyesh

**Review by geoknee — APPROVED** [review]

**Pull request merged**
