### PR TITLE
Add Mode mainnet

### PR DESCRIPTION
**Pull request by ssallam**
**Description**

Adding Mode mainnet to superchain registry.

Addresses and rollup can be verified here:
https://github.com/mode-network/chain-deployments/blob/main/mainnet/addresses.json
https://github.com/mode-network/chain-deployments/blob/main/mainnet/rollup.json

Used this command to generate bytecodes and genesis:

go run ./op-chain-ops/cmd/registry-data --l2-genesis=../chain-deployments/blob/main/mainnet/genesis-l2.json --bytecodes-dir=$SUPERCHAIN_REPO/superchain/extra/bytecodes --output=$SUPERCHAIN_REPO/superchain/extra/genesis/$SUPERCHAIN_TARGET/$CHAIN_NAME.json.gz

**Tests**

None

### CODE REVIEW

**Comment by agileurbanite** [comment]
:+1:

**Comment by ssallam** [comment]
[trianglesphere](https://github.com/trianglesphere) how do we get this pr approved?

**Comment by agileurbanite** [comment]
@maurelian can we get help?

**Comment by trianglesphere** [comment]
Mode is being added as part of #44

**Pull request closed without merging**
