### PR TITLE
fix(sepolia/metal+mode): update forks overrides

### PR DESCRIPTION
**Pull request by emilianobonassi**
**Description**

Update override for past forks for mode and metal testnets.

**Tests**

No test, used internal deployment/configuration artifacts.

**Additional context**

Part of the on-going MCP upgrade.

### CODE REVIEW

**Comment by emilianobonassi** [comment]
ci fails on the mode/metal guardians - taking a look

**Comment by mds1** [comment]
Thanks, I just pushed a commit that adds the the metal sepiloa genesis check back. It still fails, but would like to get that resolved here if we can. cc @geoknee for tips on debugging the genesis failures

**Review by mds1 — APPROVED** [review]
Chatted with @geoknee and the genesis check failures will be handled separately, so reverted my last commit

**Review by sbvegan — APPROVED** [review]
I can't independently verify these timestamps, so we're going with your internal deployment/configuration artifacts

**Pull request merged**
