### PR TITLE
Adding RACE Testnet for superchain-registry

### PR DESCRIPTION
**Pull request by visheshrace**
Adding RACE Testnet for superchain-registry

### CODE REVIEW

**Comment by sbvegan** [comment]
I pulled this PR down locally, ran the validation tests, and they have passed. I'm going to talk to the team to figure out what the issue is here.

**Comment by sbvegan** [comment]
@visheshrace can you rebase the latest changes on main? This https://github.com/ethereum-optimism/superchain-registry/pull/409 should fix the failing test.

**Comment by visheshrace** [comment]
hi @sbvegan, i have rebased the latest changes.

**Review by sbvegan — APPROVED** [review]
Removing the old genesis files seemed to do the trick, lgtm!

**Comment by sbvegan** [comment]
@visheshrace can you do a `rebase` instead of just merging `main`? This will make the final reviewers job easier so they can just see the files you're adding. After that we can get a final review and merge the race testnet into the repository :)

**Comment by refcell** [comment]
Looks like there's some changes that need rebasing - especially in the rust bindings area. Will review once those are fixed!

**Comment by visheshrace** [comment]
> @visheshrace can you do a `rebase` instead of just merging `main`? This will make the final reviewers job easier so they can just see the files you're adding. After that we can get a final review and merge the race testnet into the repository :)

Understood. I've rebased the testnet branch on top of the latest. Please review the changes.

**Comment by sbvegan** [comment]
@visheshrace thank you, can you please run `just codegen` in the root of the repository to update the `configs.toml`? That should fix the failing test from the changes we got from the rebase :)

**Review by refcell — COMMENTED** [review]
Once `just codegen` is run, it should update `superchain/configs/configs.toml` and the ci checks will pass :)

**Comment by visheshrace** [comment]
@sbvegan I've run codegen to update configs.toml

**Review by refcell — APPROVED** [review]
LGTM

**Review by bitwiseguy — APPROVED** [review]

**Pull request merged**
