### PR TITLE
Add Lisk Sepolia to the Superchain Registry

### PR DESCRIPTION
**Pull request by matjazv**
# Adding a New Chain
This PR adds Lisk Sepolia Testnet to the registry.

## Checklist
- [x] I have declared the chain at the appropriate [Superchain Level](../docs/glossary.md#superchain-level-and-rollup-stage).
- [x] I have run `just validate 4202` locally to ensure all local validation checks pass. 
- [x] I have run `just codegen` to ensure that the chainlist and other generated files are up-to-date and include my chain.

## Additional Information
To enable the `just add-chain` and `just codegen` commands to function correctly, I had to make a few changes:

1. [op-geth (config.go)](https://github.com/ethereum-optimism/op-geth/blob/optimism/params/config.go#L35)
- Adding Lisk Sepolia chain ID into the constants:
`LiskSepoliaChainID      = 4202`

2. [op-geth (superchain.go)](https://github.com/ethereum-optimism/op-geth/blob/optimism/params/superchain.go#L86):
- The Lisk Sepolia network has custom values for the following variables, necessitating a new `case` statement:
```
case LiskSepoliaChainID:
    out.Optimism.EIP1559Elasticity = 10
    out.Optimism.EIP1559Denominator = 50
```

Additionally, the `just validate` command also fails for some of the unit tests.

### CODE REVIEW

**Comment by matjazv** [comment]
With all recent updates, changes inside Additional Information are not needed anymore to successfully execute `just add-chain` command.

**Comment by geoknee** [comment]
> With all recent updates, changes inside Additional Information are not needed anymore to successfully execute `just add-chain` command.

This is great. We are working on a solution to the remaining CI failure.

**Comment by matjazv** [comment]
Hey @sbvegan, I've rebased the branch and reran `just codegen` and now everything seems to be fine for Lisk Sepolia.

**Review by sbvegan — APPROVED** [review]
lgtm!

**Review by bitwiseguy — APPROVED** [review]

**Pull request merged**
