### PR TITLE
adding RACE Testnet for superchain registry

### PR DESCRIPTION
**Pull request by visheshrace**
adding RACE Testnet for superchain registry

### CODE REVIEW

**Comment by sbvegan** [comment]
Noting the same things on Telegram here:
- The repo is still under development so this could be the reason for some failing checks
- How did you generate the PR? Did you use the `just` command fiile?

**Comment by visheshrace** [comment]
Hi @sbvegan,

I have already opened a pull request on the ethereum-lists chains repository:
[](https://github.com/ethereum-lists/chains/pull/5408)
Would you like me to open an additional pull request at [](https://github.com/FrederikBolding/chainlist)?

No, I did not use the 'just' command file. To generate the PR, I followed the instructions provided in the README. Specifically, I ran the script sh scripts/add-chain.sh standard. For Go validation checks, I used the command go test -run=/6806.

Please let me know if there are any further steps you would like me to take.

**Comment by RACEcommunity** [comment]
@visheshrace please go ahead and submit the pull request in the following also https://github.com/FrederikBolding/chainlist

**Comment by sbvegan** [comment]
My mistake, you had the right repository. There are different steps that are being finalized. I'm going to reach out on telegram for some details on that.

**Comment by sbvegan** [comment]
@visheshrace can you take the PR out of draft so the maintainers can review and merge it?

**Comment by visheshrace** [comment]
Hi @sbvegan,

Our ethereumlist chain request for the RACE Testnet has been merged. I have also moved this request out of draft for review.

Thanks.

**Comment by sbvegan** [comment]
@visheshrace thank you, I went ahead and reached out to the Race Team on Telegram on how we can work through this process together. We have time on the calendar for Friday morning to run through it. I'm going to close this PR so we can run through it on a fresh local environment. It looks like we have the prerequisites all together, so please just come Friday with the all of the environment variables locally available. See you then!

**Pull request closed without merging**
