### PR TITLE
Adding RACE Mainnet for superchain-registry

### PR DESCRIPTION
**Pull request by visheshrace**
Adding RACE Mainnet for superchain-registry

### CODE REVIEW

**Comment by sbvegan** [comment]
I'll take a look at this one after https://github.com/ethereum-optimism/superchain-registry/pull/402 merges. I expect the need to rebase on `main` and run `just codegen`.

**Comment by refcell** [comment]
Once rebased on main and codegen is run, this should be GTG.

**Comment by sbvegan** [comment]
@visheshrace https://github.com/ethereum-optimism/superchain-registry/pull/402 is clear, can you run do the following steps outlined above and then we can get this in?

**Comment by visheshrace** [comment]
> @visheshrace #402 is clear, can you run do the following steps outlined above and then we can get this in?

@sbvegan rebase and codegen done. All ci checks passesd. Please check

**Review by refcell — APPROVED** [review]
LGTM

**Review by sbvegan — APPROVED** [review]
lgtm

**Review by bitwiseguy — APPROVED** [review]

**Comment by sbvegan** [comment]
@visheshrace can you please update your branch by rebasing the latest updates on main? the repo policy won't let us merge without being updated to trunk

**Comment by visheshrace** [comment]
> @visheshrace can you please update your branch by rebasing the latest updates on main? the repo policy won't let us merge without being updated to trunk

I’ve rebased my branch with the latest updates from the main.

**Pull request merged**
